name = "prepathon-backend"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]
dev.port = 5000

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "prepathon-db"
database_id = "b7d431e3-1a01-4945-ac1c-defec4f43e89"
migrations_dir = "drizzle"

# [ai]
# binding = "AI"